server:
  port: 9000

spring:
  application:
    name: api-gateway


  # Disable cloud config
  cloud:
    config:
      enabled: false

# JWT configuration using .env variables - must match auth-service configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.nova_pioneers.api_gateway: DEBUG
