server:
  port: 9000

spring:
  application:
    name: api-gateway

  # Database configuration for token validation
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA configuration for token entity
  jpa:
    hibernate:
      ddl-auto: none  # Don't change schema, using auth-service's schema
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Disable cloud config
  cloud:
    config:
      enabled: false

# JWT configuration - must match auth-service configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.nova_pioneers.api_gateway: DEBUG