server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:dev}
spring:
  application:
    name: api-gateway

  # Database configuration using .env variables
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:novadb}
    username: ${DB_USER:pioneer}
    password: ${DB_PASSWORD:nova25!X}
    driver-class-name: org.postgresql.Driver

  # JPA configuration for token entity
  jpa:
    hibernate:
      ddl-auto: none  # Don't change schema, using auth-service's schema
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Disable cloud config
  cloud:
    config:
      enabled: false

# JWT configuration using .env variables - must match auth-service configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.nova_pioneers.api_gateway: DEBUG
