services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: pioneer
      POSTGRES_PASSWORD: nova25!X
      POSTGRES_DB: novadb
    ports:
      - "5431:5432"   ##avoids conflict with running local postgresql db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/novadb
      SPRING_DATASOURCE_USERNAME: pioneer
      SPRING_DATASOURCE_PASSWORD: nova25!X
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "http://backend:8080"
volumes:
  postgres-data:


