#this will be moved to the root of the project (frontend backend)

version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: novadb
      POSTGRES_USER: pioneer
      POSTGRES_PASSWORD: dbpassword_v1
    ports:
      - "5433:5432" #to avoid conflict with postgres locally ...
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: springboot_backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"

volumes:
  postgres_data:
