services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: pioneer
      POSTGRES_PASSWORD: nova25!X
      POSTGRES_DB: novadb
    ports:
      - "5431:5432"   ##avoids conflict with running local postgresql db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/novadb
      SPRING_DATASOURCE_USERNAME: pioneer
      SPRING_DATASOURCE_PASSWORD: nova25!X
  frontend:
    container_name: nova-pioneers-front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app  # Syncs frontend files
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true  # Fixes file watching issues
      - CHOKIDAR_USEPOLLING=1  # Ensures changes are detected in Docker
      - VITE_PORT=5173
    command: [ "npm", "run", "dev", "--", "--host" ]
volumes:
  postgres-data:


