services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin-service:
    container_name: admin-service
    build: ./backend-services/admin-service
    ports:
      - "9091:9091"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: ${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}
      FILE_UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ./backend-services/admin-service/src/main/resources/uploads:/app/uploads
      - ./backend-services/admin-service/src:/build/src
      - ./backend-services/admin-service/target:/build/target
      - maven-repo:/root/.m2/repository

  auth-service:
    container_name: auth-service
    build: ./backend-services/auth-service
    ports:
      - "9092:9092"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: ${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      FILE_UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ./backend-services/auth-service/src/main/resources/uploads:/app/uploads
      - ./backend-services/auth-service/src:/build/src
      - ./backend-services/auth-service/target:/build/target
      - maven-repo:/root/.m2/repository

  parents-kids-service:
    container_name: parents-kids-service
    build: ./backend-services/parents_kids-service
    ports:
      - "9093:9093"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: ${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}
      FILE_UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ./backend-services/parents_kids-service/src/main/resources/uploads:/app/uploads
      - ./backend-services/parents_kids-service/src:/build/src
      - ./backend-services/parents_kids-service/target:/build/target
      - maven-repo:/root/.m2/repository

  teachers-courses-service:
    container_name: teachers-courses-service
    build: ./backend-services/teachers_courses-service
    ports:
      - "9094:9094"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: ${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}
      FILE_UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ./backend-services/teachers_courses-service/src/main/resources/uploads:/app/uploads
      - ./backend-services/teachers_courses-service/src:/build/src
      - ./backend-services/teachers_courses-service/target:/build/target
      - maven-repo:/root/.m2/repository

  api-gateway:
    build:
      context: ./backend-services/api-gateway
    environment:
      ADMIN_SERVICE_URI: ${ADMIN_SERVICE_URI}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      PARENTS_KIDS_SERVICE_URI: ${PARENTS_KIDS_SERVICE_URI}
      TEACHERS_COURSES_SERVICE_URI: ${TEACHERS_COURSES_SERVICE_URI}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DEVTOOLS_RESTART_ENABLED: ${SPRING_DEVTOOLS_RESTART_ENABLED}
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: ${SPRING_DEVTOOLS_LIVERELOAD_ENABLED}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
      admin-service:
        condition: service_started
      auth-service:
        condition: service_started
      parents-kids-service:
        condition: service_started
      teachers-courses-service:
        condition: service_started
    volumes:
      - ./backend-services/api-gateway/src:/app/src
      - ./backend-services/api-gateway/target:/app/target
      - maven-repo:/root/.m2/repository

  frontend:
    container_name: nova-pioneers-front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=1
      - VITE_PORT=5173
    command: [ "npm", "run", "dev", "--", "--host" ]

volumes:
  postgres-data:
  maven-repo: