# Update application.yml
server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,loggers
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:dev}


spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: teachers_courses-service

  # File upload configuration - IMPORTANT
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB # Increased for multiple files
      max-request-size: 100MB # Total request size
      file-size-threshold: 2KB
      location: ${java.io.tmpdir} # Temporary storage during upload

# File upload directory - THIS IS KEY
file:
  upload-dir: ./uploads
